/*
  # Creare tabele pentru Quiz MV 2025
  1. Purpose: Configurarea structurii bazei de date pentru aplicația Quiz MV 2025
  2. Schema: sections, questions, answers
  3. Security: RLS activat pentru toate tabelele
*/

-- Crearea tabelei pentru secțiuni
CREATE TABLE IF NOT EXISTS sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  "order" INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Crearea tabelei pentru întrebări
CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id BIGINT REFERENCES sections(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Crearea tabelei pentru răspunsuri
CREATE TABLE IF NOT EXISTS answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,
  answer_text TEXT NOT NULL,
  is_correct BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Activarea Row Level Security pentru toate tabelele
ALTER TABLE sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE answers ENABLE ROW LEVEL SECURITY;

-- Politici de securitate pentru tabela sections
CREATE POLICY "Oricine poate vizualiza secțiunile" 
  ON sections FOR SELECT 
  USING (true);

CREATE POLICY "Doar utilizatorii autentificați pot modifica secțiunile" 
  ON sections FOR ALL 
  USING (auth.role() = 'authenticated');

-- Politici de securitate pentru tabela questions
CREATE POLICY "Oricine poate vizualiza întrebările" 
  ON questions FOR SELECT 
  USING (true);

CREATE POLICY "Doar utilizatorii autentificați pot modifica întrebările" 
  ON questions FOR ALL 
  USING (auth.role() = 'authenticated');

-- Politici de securitate pentru tabela answers
CREATE POLICY "Oricine poate vizualiza răspunsurile" 
  ON answers FOR SELECT 
  USING (true);

CREATE POLICY "Doar utilizatorii autentificați pot modifica răspunsurile" 
  ON answers FOR ALL 
  USING (auth.role() = 'authenticated');
